[tool.poetry]
name = "maksgit"
version = "0.1.0"
description = ""
authors = ["belogur.bi <belogur.bi@intechs.by>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
